---
title: "taylor_lyrics_df"
author: "Tilina Alzaben"
date: "2023-12-01"
output: html_document
--- 

```{r, message = FALSE}
# Install the necessary packages if not already installed
install.packages("purrr")
install.packages("dplyr")

# Load the necessary libraries
library(purrr)
library(dplyr)
```

```{r, message = FALSE}
# Read all CSV files and combine them into a single data frame using map_df'
files <- list.files(path = "data", pattern = "\\.csv$", full.names = TRUE)
combined_data <- map_df(files, read.csv)
```

```{r, message = FALSE}
# Group the combined data by album_name and track_title
# Create a new column 'chunk' to identify chunks of 3 lines based on the 'line' column
# Group by album_name, track_title, and chunk, then summarize to combine lyrics into one string
combined_data <- combined_data %>%
  group_by(album_name, track_title) %>%
  mutate(chunk = ceiling(line / 3)) %>%
  group_by(album_name, track_title, chunk) %>%
  summarize(combined_lyrics = paste0(lyric, collapse = " ")) %>%
  ungroup()

# Display the first few rows of the data frame
head(combined_data)
```

# Eras recoding

```{r}
# Use the recode function to recode the albums 
combined_data_all_eras <- combined_data %>%
  mutate(album_name = recode(album_name,
    "1989 (Deluxe)"                = 4,
    "Fearless (Taylor’s Version)"  = 1,
    "Lover"                        = 6,
    "Red (Deluxe Edition)"         = 3,
    "Speak Now (Deluxe)"           = 2,
    "Taylor Swift"                 = 0,
    "evermore (deluxe version)"    = 8,
    "folklore (deluxe version)"    = 7,
    "reputation"                   = 5
  ))

# Print out all unique album names
unique_albums <- unique(combined_data_all_eras$album_name)
print(unique_albums)
```

```{r}
# Filter the data for fine-tuning BERT and GPT2
fine_tune_data <- na.omit(subset(combined_data, select = c(1, 4)))
names(fine_tune_data) <- c("label", "text")
write.csv(fine_tune_data, "data/fine_tune_data_all_eras.csv")
```

# Biber recoding

```{r}
# Use the recode function to recode
# This recoding uses the Biber stickplot similarity to group albums
combined_data_biber <- combined_data %>%
  mutate(album_name = recode(album_name,
    "1989 (Deluxe)"                = 1,
    "Fearless (Taylor’s Version)"  = 0,
    "Lover"                        = 1,
    "Red (Deluxe Edition)"         = 2,
    "Speak Now (Deluxe)"           = 1,
    "Taylor Swift"                 = 0,
    "evermore (deluxe version)"    = 2,
    "folklore (deluxe version)"    = 2,
    "reputation"                   = 1
  ))

# Print out all unique album names
unique_albums <- unique(combined_data_biber$album_name)
print(unique_albums)
```

```{r}
# Filter the data for fine-tuning BERT and GPT2
fine_tune_data_biber <- na.omit(subset(combined_data_biber, select = c(1, 4)))
names(fine_tune_data_biber) <- c("label", "text")
write.csv(fine_tune_data_biber, "data/fine_tune_data_biber.csv")
```


# Genre recoding

```{r}
# Use the recode function to recode
# This recoding uses primary genre of the album to group albums
combined_data_genre <- combined_data %>%
  mutate(album_name = recode(album_name,
    "1989 (Deluxe)"                = 1,
    "Fearless (Taylor’s Version)"  = 0,
    "Lover"                        = 1,
    "Red (Deluxe Edition)"         = 1,
    "Speak Now (Deluxe)"           = 1,
    "Taylor Swift"                 = 0,
    "evermore (deluxe version)"    = 2,
    "folklore (deluxe version)"    = 2,
    "reputation"                   = 1
  ))

# Print out all unique album names
unique_albums <- unique(combined_data_genre$album_name)
print(unique_albums)
```

```{r}
# Filter the data for fine-tuning BERT and GPT2
fine_tune_data_genre <- na.omit(subset(combined_data_genre, select = c(1, 4)))
names(fine_tune_data_genre) <- c("label", "text")
write.csv(fine_tune_data_genre, "data/fine_tune_data_genre.csv")
```